return {
  version = "1.9",
  luaversion = "5.1",
  tiledversion = "1.9.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "left-up",
  width = 34,
  height = 200,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 18,
  nextobjectid = 430,
  properties = {},
  tilesets = {
    {
      name = "testTileset",
      firstgid = 1,
      class = "",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 16,
      image = "testTileset.png",
      imagewidth = 256,
      imageheight = 352,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      wangsets = {},
      tilecount = 352,
      tiles = {}
    }
  },
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 14,
      name = "Players",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 111,
          name = "PlayerB",
          class = "",
          shape = "rectangle",
          x = 402.834,
          y = 2229.66,
          width = 22,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {
            ["attackKey"] = "m",
            ["colorB"] = 0,
            ["colorG"] = 1,
            ["colorR"] = 1,
            ["jumpKey"] = "up",
            ["leftMovementKey"] = "left",
            ["rightMovementKey"] = "right"
          }
        },
        {
          id = 109,
          name = "PlayerA",
          class = "",
          shape = "rectangle",
          x = 113.001,
          y = 2229.76,
          width = 24,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {
            ["attackKey"] = "e",
            ["colorB"] = 1,
            ["colorG"] = 0,
            ["colorR"] = 0,
            ["jumpKey"] = "w",
            ["leftMovementKey"] = "a",
            ["rightMovementKey"] = "d"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 12,
      name = "Wall",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 94,
          name = "2",
          class = "",
          shape = "rectangle",
          x = -16,
          y = -0.666667,
          width = 48,
          height = 3200.67,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 95,
          name = "1",
          class = "",
          shape = "rectangle",
          x = 512,
          y = 1.33333,
          width = 48,
          height = 3198.67,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 225,
          name = "",
          class = "",
          shape = "rectangle",
          x = 176.667,
          y = 2790,
          width = 32,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 226,
          name = "",
          class = "",
          shape = "rectangle",
          x = 336.667,
          y = 2790,
          width = 32,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 240,
          name = "",
          class = "",
          shape = "rectangle",
          x = 144,
          y = 2480,
          width = 34,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 241,
          name = "",
          class = "",
          shape = "rectangle",
          x = 47.3333,
          y = 2351.33,
          width = 16,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 245,
          name = "",
          class = "",
          shape = "rectangle",
          x = 62,
          y = 2672,
          width = 34,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 246,
          name = "",
          class = "",
          shape = "rectangle",
          x = 353.333,
          y = 2479.33,
          width = 29.3333,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 250,
          name = "",
          class = "",
          shape = "rectangle",
          x = 448,
          y = 2672.67,
          width = 30.6667,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 252,
          name = "",
          class = "",
          shape = "rectangle",
          x = 481.333,
          y = 2352,
          width = 16,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 273,
          name = "",
          class = "",
          shape = "rectangle",
          x = 239.663,
          y = 349.334,
          width = 16.3333,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 274,
          name = "",
          class = "",
          shape = "rectangle",
          x = 319.33,
          y = 350,
          width = 14,
          height = 31,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 275,
          name = "",
          class = "",
          shape = "rectangle",
          x = 207.663,
          y = 495.001,
          width = 12.6667,
          height = 31.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 276,
          name = "",
          class = "",
          shape = "rectangle",
          x = 352.33,
          y = 495.334,
          width = 16,
          height = 32.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 278,
          name = "",
          class = "",
          shape = "rectangle",
          x = 223.663,
          y = 1260.67,
          width = 17.3333,
          height = 32.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 279,
          name = "",
          class = "",
          shape = "rectangle",
          x = 336.33,
          y = 1262,
          width = 18,
          height = 31.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 281,
          name = "",
          class = "",
          shape = "rectangle",
          x = 173.663,
          y = 1421.32,
          width = 19.3333,
          height = 31.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 282,
          name = "",
          class = "",
          shape = "rectangle",
          x = 374.664,
          y = 1423.66,
          width = 13.3333,
          height = 29,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 283,
          name = "",
          class = "",
          shape = "rectangle",
          x = 224.33,
          y = 1518.33,
          width = 14.3333,
          height = 32.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 284,
          name = "",
          class = "",
          shape = "rectangle",
          x = 339.33,
          y = 1518.99,
          width = 14.6667,
          height = 32.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 285,
          name = "",
          class = "",
          shape = "rectangle",
          x = 175.996,
          y = 1661.33,
          width = 15.6667,
          height = 31.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 286,
          name = "",
          class = "",
          shape = "rectangle",
          x = 366.33,
          y = 1659.66,
          width = 17.6667,
          height = 34.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 287,
          name = "",
          class = "",
          shape = "rectangle",
          x = 254.83,
          y = 1805.82,
          width = 15.3333,
          height = 31.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 289,
          name = "",
          class = "",
          shape = "rectangle",
          x = 309.08,
          y = 1806.15,
          width = 13.3333,
          height = 31.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 290,
          name = "",
          class = "",
          shape = "rectangle",
          x = 170.663,
          y = 1873.32,
          width = 19,
          height = 32.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 291,
          name = "",
          class = "",
          shape = "rectangle",
          x = 366.663,
          y = 1874.66,
          width = 12.3333,
          height = 31,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 297,
          name = "",
          class = "",
          shape = "rectangle",
          x = 195,
          y = 189.34,
          width = 14,
          height = 31.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 300,
          name = "",
          class = "",
          shape = "rectangle",
          x = 82.6667,
          y = 284.67,
          width = 16.3333,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 303,
          name = "",
          class = "",
          shape = "rectangle",
          x = 80,
          y = 2527,
          width = 15.6667,
          height = 32.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 304,
          name = "",
          class = "",
          shape = "rectangle",
          x = 430.333,
          y = 2527.33,
          width = 16.6667,
          height = 31.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 305,
          name = "",
          class = "",
          shape = "rectangle",
          x = 112.667,
          y = 2837.67,
          width = 30,
          height = 32.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 306,
          name = "",
          class = "",
          shape = "rectangle",
          x = 416.334,
          y = 2838,
          width = 16.3333,
          height = 31.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 328,
          name = "",
          class = "",
          shape = "rectangle",
          x = 144,
          y = 2208,
          width = 31.9999,
          height = 80.3031,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 333,
          name = "",
          class = "",
          shape = "rectangle",
          x = 451.333,
          y = 284.34,
          width = 16,
          height = 30.6666,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 335,
          name = "",
          class = "",
          shape = "rectangle",
          x = 481.333,
          y = 188,
          width = 32,
          height = 33.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 336,
          name = "",
          class = "",
          shape = "rectangle",
          x = 34.6667,
          y = 186.67,
          width = 38,
          height = 34,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 342,
          name = "",
          class = "",
          shape = "rectangle",
          x = 339.333,
          y = 187.34,
          width = 17.3333,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 343,
          name = "14",
          class = "",
          shape = "rectangle",
          x = 324.667,
          y = 187.33,
          width = 32.6663,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 356,
          name = "",
          class = "",
          shape = "rectangle",
          x = 161.917,
          y = -83.42,
          width = 18,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 360,
          name = "",
          class = "",
          shape = "rectangle",
          x = 64.6667,
          y = 186,
          width = 15.3333,
          height = 34.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 361,
          name = "",
          class = "",
          shape = "rectangle",
          x = 465.334,
          y = 188,
          width = 16,
          height = 32.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 363,
          name = "",
          class = "",
          shape = "rectangle",
          x = 317.334,
          y = 75.34,
          width = 3.33333,
          height = 31.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 364,
          name = "",
          class = "",
          shape = "rectangle",
          x = 228,
          y = 75.34,
          width = 3.33333,
          height = 31.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 365,
          name = "",
          class = "",
          shape = "rectangle",
          x = 231.333,
          y = 75.33,
          width = 86,
          height = 30.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 369,
          name = "",
          class = "",
          shape = "rectangle",
          x = 386.916,
          y = -82.71,
          width = 16,
          height = 30.75,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 370,
          name = "",
          class = "",
          shape = "rectangle",
          x = 418.958,
          y = 1730.21,
          width = 18,
          height = 30,
          rotation = 0,
          visible = false,
          properties = {}
        },
        {
          id = 371,
          name = "18",
          class = "",
          shape = "rectangle",
          x = 386.667,
          y = -82.71,
          width = 69.6667,
          height = 30.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 372,
          name = "",
          class = "",
          shape = "rectangle",
          x = 208,
          y = 2032,
          width = 15.3333,
          height = 31.7878,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 373,
          name = "",
          class = "",
          shape = "rectangle",
          x = 320,
          y = 2032,
          width = 16.0606,
          height = 31.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 375,
          name = "",
          class = "",
          shape = "rectangle",
          x = 435.625,
          y = -132,
          width = 33.3333,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 377,
          name = "",
          class = "",
          shape = "rectangle",
          x = 98.6667,
          y = -132,
          width = 30.6667,
          height = 78.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 383,
          name = "",
          class = "",
          shape = "rectangle",
          x = 32,
          y = 2128.17,
          width = 32.3333,
          height = 79.5606,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 399,
          name = "",
          class = "",
          shape = "rectangle",
          x = 368,
          y = 2208,
          width = 30.4999,
          height = 80.3031,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 400,
          name = "",
          class = "",
          shape = "rectangle",
          x = 368.303,
          y = 2208.2,
          width = 29.8333,
          height = 14.8485,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 417,
          name = "",
          class = "",
          shape = "rectangle",
          x = 480.663,
          y = 2112.07,
          width = 32.3333,
          height = 79.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 425,
          name = "",
          class = "",
          shape = "rectangle",
          x = 80,
          y = 2016.18,
          width = 31.625,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 426,
          name = "",
          class = "",
          shape = "rectangle",
          x = 80,
          y = 2176,
          width = 16,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 427,
          name = "",
          class = "",
          shape = "rectangle",
          x = 112,
          y = 2112.18,
          width = 15.6364,
          height = 31.4545,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 428,
          name = "",
          class = "",
          shape = "rectangle",
          x = 95.6364,
          y = 2016,
          width = 16.1818,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 9,
      name = "Ground",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 93,
          name = "1",
          class = "",
          shape = "rectangle",
          x = -0.666667,
          y = 2964,
          width = 544,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 148,
          name = "4",
          class = "",
          shape = "rectangle",
          x = 32,
          y = 2672,
          width = 64.6667,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 151,
          name = "7",
          class = "",
          shape = "rectangle",
          x = 31.3333,
          y = 2351.33,
          width = 29.3333,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 155,
          name = "10",
          class = "",
          shape = "rectangle",
          x = 448,
          y = 2672.67,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 158,
          name = "13",
          class = "",
          shape = "rectangle",
          x = 480,
          y = 2351.33,
          width = 31.3333,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 159,
          name = "14",
          class = "",
          shape = "rectangle",
          x = 194.667,
          y = 188.67,
          width = 30.6663,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 160,
          name = "15",
          class = "",
          shape = "rectangle",
          x = 50,
          y = 285,
          width = 49.3333,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 161,
          name = "16",
          class = "",
          shape = "rectangle",
          x = 452.666,
          y = 284.33,
          width = 45.9999,
          height = 30.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 163,
          name = "18",
          class = "",
          shape = "rectangle",
          x = 114.001,
          y = -83.67,
          width = 64.3333,
          height = 30.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 168,
          name = "23",
          class = "",
          shape = "rectangle",
          x = 107.997,
          y = 1873.65,
          width = 80.6667,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 169,
          name = "24",
          class = "",
          shape = "rectangle",
          x = 107.329,
          y = 1824.32,
          width = 32,
          height = 81.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 170,
          name = "25",
          class = "",
          shape = "rectangle",
          x = 411.184,
          y = 1906.67,
          width = 88,
          height = 32,
          rotation = 270.177,
          visible = true,
          properties = {}
        },
        {
          id = 171,
          name = "26",
          class = "",
          shape = "rectangle",
          x = 366.505,
          y = 1906.2,
          width = 31,
          height = 76.6687,
          rotation = 270.177,
          visible = true,
          properties = {}
        },
        {
          id = 172,
          name = "27",
          class = "",
          shape = "rectangle",
          x = 254.33,
          y = 1805.07,
          width = 66.9166,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 173,
          name = "28",
          class = "",
          shape = "rectangle",
          x = 114.998,
          y = 1661.32,
          width = 78,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 174,
          name = "29",
          class = "",
          shape = "rectangle",
          x = 115.329,
          y = 1611.99,
          width = 33,
          height = 81.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 175,
          name = "30",
          class = "",
          shape = "rectangle",
          x = 415.327,
          y = 1693.33,
          width = 90,
          height = 36.6667,
          rotation = 270,
          visible = true,
          properties = {}
        },
        {
          id = 176,
          name = "31",
          class = "",
          shape = "rectangle",
          x = 365.996,
          y = 1694.99,
          width = 35,
          height = 86,
          rotation = 270,
          visible = true,
          properties = {}
        },
        {
          id = 177,
          name = "32",
          class = "",
          shape = "rectangle",
          x = 224.33,
          y = 1518.66,
          width = 129,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 183,
          name = "34",
          class = "",
          shape = "rectangle",
          x = 116.999,
          y = 1373.82,
          width = 32,
          height = 78.6666,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 184,
          name = "35",
          class = "",
          shape = "rectangle",
          x = 414.329,
          y = 1453.49,
          width = 88,
          height = 36.6667,
          rotation = 270,
          visible = true,
          properties = {}
        },
        {
          id = 185,
          name = "36",
          class = "",
          shape = "rectangle",
          x = 375.333,
          y = 1454.15,
          width = 29.6667,
          height = 75.3333,
          rotation = 270,
          visible = true,
          properties = {}
        },
        {
          id = 186,
          name = "37",
          class = "",
          shape = "rectangle",
          x = 116.997,
          y = 1421.32,
          width = 76,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 187,
          name = "38",
          class = "",
          shape = "rectangle",
          x = 223.33,
          y = 1261.67,
          width = 131,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 189,
          name = "40",
          class = "",
          shape = "rectangle",
          x = 127.164,
          y = 446.667,
          width = 33.6667,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 190,
          name = "42",
          class = "",
          shape = "rectangle",
          x = 127.162,
          y = 494.837,
          width = 94,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 191,
          name = "42",
          class = "",
          shape = "rectangle",
          x = 352.871,
          y = 527.813,
          width = 31.0169,
          height = 78.6501,
          rotation = 270.476,
          visible = true,
          properties = {}
        },
        {
          id = 192,
          name = "43",
          class = "",
          shape = "rectangle",
          x = 403.563,
          y = 527.541,
          width = 86.6667,
          height = 28.6668,
          rotation = 270.476,
          visible = true,
          properties = {}
        },
        {
          id = 197,
          name = "44",
          class = "",
          shape = "rectangle",
          x = 240.162,
          y = 349.5,
          width = 93.3333,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 227,
          name = "",
          class = "",
          shape = "rectangle",
          x = 176.667,
          y = 2790,
          width = 32,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 228,
          name = "",
          class = "",
          shape = "rectangle",
          x = 336.667,
          y = 2790,
          width = 32,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 229,
          name = "",
          class = "",
          shape = "rectangle",
          x = 336.667,
          y = 2838,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 230,
          name = "",
          class = "",
          shape = "rectangle",
          x = 114,
          y = 2838,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 237,
          name = "",
          class = "",
          shape = "rectangle",
          x = 80,
          y = 2526.67,
          width = 82,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 239,
          name = "",
          class = "",
          shape = "rectangle",
          x = 144.667,
          y = 2480,
          width = 33.3333,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 248,
          name = "",
          class = "",
          shape = "rectangle",
          x = 367.333,
          y = 2527.33,
          width = 80,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 249,
          name = "",
          class = "",
          shape = "rectangle",
          x = 353.333,
          y = 2479.33,
          width = 30,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 257,
          name = "",
          class = "",
          shape = "rectangle",
          x = 411.413,
          y = 1818.49,
          width = 32,
          height = 14.25,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 259,
          name = "",
          class = "",
          shape = "rectangle",
          x = 107.663,
          y = 1824.66,
          width = 31.6667,
          height = 13.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 260,
          name = "",
          class = "",
          shape = "rectangle",
          x = 114.996,
          y = 1611.99,
          width = 33.3333,
          height = 16.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 261,
          name = "",
          class = "",
          shape = "rectangle",
          x = 415.33,
          y = 1602.33,
          width = 36.6667,
          height = 18,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 262,
          name = "",
          class = "",
          shape = "rectangle",
          x = 117.664,
          y = 1374.66,
          width = 31.6666,
          height = 16.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 264,
          name = "",
          class = "",
          shape = "rectangle",
          x = 413.997,
          y = 1365,
          width = 37.6666,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 265,
          name = "",
          class = "",
          shape = "rectangle",
          x = 127.997,
          y = 447.334,
          width = 33,
          height = 15,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 267,
          name = "",
          class = "",
          shape = "rectangle",
          x = 404.33,
          y = 439.333,
          width = 27.6667,
          height = 16.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 324,
          name = "",
          class = "",
          shape = "rectangle",
          x = 96.334,
          y = 2256.81,
          width = 15.6667,
          height = 31.7499,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 325,
          name = "",
          class = "",
          shape = "rectangle",
          x = 96,
          y = 2256.73,
          width = 63.3333,
          height = 31.5833,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 357,
          name = "",
          class = "",
          shape = "rectangle",
          x = 144.303,
          y = 2208.2,
          width = 31.3333,
          height = 14.8485,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 381,
          name = "",
          class = "",
          shape = "rectangle",
          x = 48.5833,
          y = 2176.24,
          width = 47.5682,
          height = 31.4886,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 388,
          name = "",
          class = "",
          shape = "rectangle",
          x = 32,
          y = 2128,
          width = 32.3333,
          height = 15.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 402,
          name = "",
          class = "",
          shape = "rectangle",
          x = 431.333,
          y = 2256.48,
          width = 15.6667,
          height = 32.4166,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 403,
          name = "",
          class = "",
          shape = "rectangle",
          x = 383.667,
          y = 2255.9,
          width = 63.3333,
          height = 32.5833,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 405,
          name = "",
          class = "",
          shape = "rectangle",
          x = 480.693,
          y = 2112,
          width = 32,
          height = 15.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 406,
          name = "",
          class = "",
          shape = "rectangle",
          x = 448,
          y = 2159.66,
          width = 48.1137,
          height = 32.0909,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 421,
          name = "",
          class = "",
          shape = "rectangle",
          x = 207.667,
          y = 2032,
          width = 128.333,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 423,
          name = "",
          class = "",
          shape = "rectangle",
          x = 112,
          y = 2112,
          width = 31.3333,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 17,
      name = "Camera",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 119,
          name = "1",
          class = "",
          shape = "point",
          x = 272.667,
          y = 2614,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 195,
          name = "2",
          class = "",
          shape = "point",
          x = 285.999,
          y = 2128.01,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 203,
          name = "3",
          class = "",
          shape = "point",
          x = 272.997,
          y = 1862.66,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 204,
          name = "4",
          class = "",
          shape = "point",
          x = 286.997,
          y = 1452.66,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 205,
          name = "5",
          class = "",
          shape = "point",
          x = 286.997,
          y = 670.667,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 206,
          name = "6",
          class = "",
          shape = "point",
          x = 286.33,
          y = 250,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
