engine = Engine()

engine:addEntity(ground)
engine:addEntity(player)
--engine:addEntity(player2)
--engine:addEntity(player3)
engine:addSystem(GravitySystem())
engine:addSystem(JumpSystem())
engine:addSystem(GroundCollisionSystem())
engine:addSystem(WallCollisionSystem())
engine:addSystem(DrawingSystem(), "draw")
engine:addSystem(MovementSystem())